language: node_js
node_js:
  - "9"

branches:
  only: 
    - master

cache: yarn

install: yarn
script:
  - yarn lint
  - yarn test

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "9"
      script: 
        - yarn test
        - yarn build
        - yarn deploy
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
